{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ include "service.name" . }}
    service: {{ template "service.fullname" . }}
    managed-by: {{ .Release.Service }}
{{- end -}}
